

from google.adk.tools.tool_context import ToolContext
from google.adk.tools.base_tool import BaseTool
from typing import Any, Dict, Optional, Literal
# from mcp.types import CallToolResult
import base64
import json
import google.genai.types as types
from toon import encode, decode
import asyncio
import gzip
import plotly.io as pio
from google.genai.types import Part
#from mcp.types import CallToolResult
from google.adk.agents.callback_context import CallbackContext
from google.adk.tools.mcp_tool.mcp_toolset import McpToolset, StreamableHTTPConnectionParams, StdioServerParameters, StdioConnectionParams
from google.adk.models import LlmResponse, LlmRequest
from pydantic import BaseModel, ValidationError, Field
from pydantic import TypeAdapter
from typing import Optional, Any, Dict
from pydantic import BaseModel, Field, ConfigDict, field_validator, ValidationError
import os

user = os.environ.get('username')
db_pass = os.environ.get('db_passward')
connection = os.environ.get('connection_name')
db_name = os.environ.get('database_name')


class VIZ_INPUT(BaseModel):
    viz_requested : str
    last_validated_sql: str
    table_schema_artifact: str


class MainRouter(BaseModel):
    intent: Literal['SQL_ONLY', 'SQL_AND_VIZ',  'CLARITY'] = Field(description = """Intent Extracted from current user query.
                                                                  - 'SQL_ONLY': if intent is only to generate sql query from user query.
                                                                  - 'SQL_AND_VIZ': if user intent is to generate sql and visulaize data in graph or plot form.
                                                                  - 'CLARITY': if need more clarification to generate sql.""",)
    last_validated_sql: Optional[str] = Field(
        description="""
        Final validated SQL query generated by SQL_SPECIALIST tool.
        Update ONLY after SQL is successfully validated.
        """
    ),
    table_schema_artifact: str = Field(
        description="""
        Artifact Id of table schema in database.
        """
    ),
    current_invocation_query: str = Field(
        description="""
        Latest user query.
        MUST always contain the current user input.
        """
    ),
    last_invocation_query: Optional[str] = Field(
        description="""
        Previous user query.
        Before updating current_invocation_query, copy its old value here.
        """,
        default = None
    ),
    user_session_summary: Optional[str] = Field(
        description="""
        Compact summary of entire conversation so far.
        Update after every user interaction.
        Keep it short but meaningful.
        """
    ),
    viz_requested: Optional[Literal["bar_chart", "line_chart", "pie_chart", "table", "none"]] = Field(
        description="""
        Type of visualization requested by user.

        Explicit VIX Keywards:
        plot, chart, graph, visulaization, dashboard, trend line, bar chart, line chart, scatter, histogram.

        Choose:
        - bar_chart: comparison across categories
        - line_chart: trends over time
        - pie_chart: proportions
        - table: tabular output requested
        - none: no visualization requested

        If user does not explicitly mention visualization, use 'none'.
        """,
        default = None
    ),
    clarifying_question: Optional[str] = Field(
        description="""
        Ask a question ONLY if user query is ambiguous or missing required info
        to generate SQL.

        Examples:
        - missing table
        - unclear column
        - ambiguous metric

        If query is clear → set to None.
        """,
        default = None
    ),
    MAX_RETRIES: int = 3,
    MAX_VIZ_RETRIES: int = 3,
    assumptions: Optional[str] = Field(
        description = "assumption for final generated sql query"
    ),
    final_query_status: Literal['SUCCESS', 'FAIL_NEEDS_CLARIFICATION', 'FAIL_MAX_RETRIES'] = Field(
        description = 'status of generated sql query'
    ),
    VIZ_STATUS: Literal['SUCCESS','FAIL_MAX_RETRIES'] = Field(
        description = """Status of visulaization agent"""
    ),
    VIZ_artifact: Optional[str] = Field(
        description = """Arifact ID of visualization""", default = None
    )

    @field_validator('table_schema_artifact')
    @classmethod
    def validate_database_schema(cls, v: str) -> str:
        if not v.lower().endswith('.json'):
            raise ValueError("database_schema artifact id not ends with .json")
        return v
    
    @field_validator('VIZ_artifact')
    @classmethod
    def viz_artifact_check(cls, v: str) -> str:
        if not v.lower().endswith('.png'):
            raise ValueError("Artifact ID of visualization is not ends with .png")
        return v



async def set_state(tool_context: ToolContext, updates: MainRouter) -> dict:
    """
    Update the application state with specific allowed keys.
    
    Returns:
        Status message
    """
    try:
        if not isinstance(updates, MainRouter):
            updates = MainRouter.model_validate(updates)
        
        data_to_apply = updates.model_dump(exclude_unset=True)

        for k, v in data_to_apply.items():
            tool_context.state[k] = v
        
        return {"status": "success",
            "updated_keys": f"{",".join(list(data_to_apply.keys()))}"}
    
    except ValidationError as e:
        return {"status": "failed", "error": str(e)}




async def load_master_data_tool(tool_context: ToolContext, artifact_id : str) -> str:
    
    """Loads the complete, raw content of the artifact using artifact id.
    Args:
        artifact_id: artifact filename

    Returns:
        - artifact content in text format
    """
    report_artifact = await tool_context.load_artifact(filename = artifact_id)

    if report_artifact.inline_data and report_artifact.inline_data.data:
        text = report_artifact.inline_data.data.decode("utf-8")
    
    return text


async def after_tool_artifact_save(tool: BaseTool, args: dict[str, Any], tool_context: ToolContext, tool_response: Optional[Dict]) -> Optional[Dict]:
    """
    Inspects/modifies the tool result after execution.
    """
    agent_name = tool_context.agent_name
    tool_name = tool.name
    
    if tool_name == 'get_sql_table_schema':
        tool_result = json.loads(tool_response['content'][0]['text'])
        if tool_result['status'].lower() == 'success':
            
            report_artifact = types.Part.from_bytes(data=json.dumps(tool_result.get('data')).encode('utf-8'), mime_type="application/json")
            version = await tool_context.save_artifact(filename = "table_schema.json", artifact = report_artifact)

            tool_result['data'] = f"[User stored Artifact] Artifact filename for generated Database table schema : table_schema.json"
            return tool_result
        else:
            return tool_response
    
    if tool_name == 'execute_graph':
        tool_result = json.loads(tool_response['content'][0]['text'])
        if tool_result['status'].lower() == 'success':
            
            report_artifact = types.Part.from_bytes(data = pio.from_json(tool_result['data']).to_image(format = 'png', width = 400, height = 300), 
                                                mime_type = "image/png")
            version = await tool_context.save_artifact(filename = "visialize_data.png", artifact = report_artifact)
            tool_result['data'] = f"[User stored Artifact] Artifact filename for generated for data visualization : plotly_visualization.png"
            return tool_result
        else:
            return tool_result

    return tool_response


toolset = McpToolset(
  connection_params = StdioConnectionParams(
                    server_params = StdioServerParameters(
                        command = 'python',
                        args = [os.path.join(os.path.dirname(os.path.abspath(__file__)), "server.py")],
                        env = {"username": user,
                                "db_passward": db_pass,
                                "connection_name": connection,
                                "database_name": db_name
                                }
                    ),
                    shell = True,
                    timeout = 20,
  ),
)